unstable_features = true
imports_layout = "Vertical"
imports_granularity = "Crate"
comment_width = 120
max_width = 120
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
